/*Copyright (c) 2017-2018 multibase.pt All Rights Reserved.
 This software is the confidential and proprietary information of multibase.pt You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with multibase.pt*/
package com.faturacaomodelo.db_a_account_id;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.sql.Date;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Account generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`account`")
public class Account implements Serializable {

    private Integer id;
    private String accountName;
    private Date accountRegistrationDate;
    private Date accountTerminationDate;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`ID`", nullable = false, scale = 0, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "`account_name`", nullable = true, length = 255)
    public String getAccountName() {
        return this.accountName;
    }

    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }

    @Column(name = "`account_registration_date`", nullable = true)
    public Date getAccountRegistrationDate() {
        return this.accountRegistrationDate;
    }

    public void setAccountRegistrationDate(Date accountRegistrationDate) {
        this.accountRegistrationDate = accountRegistrationDate;
    }

    @Column(name = "`account_termination_date`", nullable = true)
    public Date getAccountTerminationDate() {
        return this.accountTerminationDate;
    }

    public void setAccountTerminationDate(Date accountTerminationDate) {
        this.accountTerminationDate = accountTerminationDate;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Account)) return false;
        final Account account = (Account) o;
        return Objects.equals(getId(), account.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}

