/*Generated by WaveMaker Studio*/
package com.faturacaomodelo.dbinvoice.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.faturacaomodelo.dbinvoice.AccountMove;
import com.faturacaomodelo.dbinvoice.AccountMoveLine;
import com.faturacaomodelo.dbinvoice.Journal;


/**
 * ServiceImpl object for domain model class Journal.
 *
 * @see Journal
 */
@Service("dbinvoice.JournalService")
public class JournalServiceImpl implements JournalService {

    private static final Logger LOGGER = LoggerFactory.getLogger(JournalServiceImpl.class);

    @Autowired
	@Qualifier("dbinvoice.AccountMoveService")
	private AccountMoveService accountMoveService;

    @Autowired
	@Qualifier("dbinvoice.AccountMoveLineService")
	private AccountMoveLineService accountMoveLineService;

    @Autowired
    @Qualifier("dbinvoice.JournalDao")
    private WMGenericDao<Journal, Integer> wmGenericDao;

    public void setWMGenericDao(WMGenericDao<Journal, Integer> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "dbinvoiceTransactionManager")
    @Override
	public Journal create(Journal journal) {
        LOGGER.debug("Creating a new Journal with information: {}", journal);
        Journal journalCreated = this.wmGenericDao.create(journal);
        if(journalCreated.getAccountMoves() != null) {
            for(AccountMove accountMove : journalCreated.getAccountMoves()) {
                accountMove.setJournal(journalCreated);
                LOGGER.debug("Creating a new child AccountMove with information: {}", accountMove);
                accountMoveService.create(accountMove);
            }
        }

        if(journalCreated.getAccountMoveLines() != null) {
            for(AccountMoveLine accountMoveLine : journalCreated.getAccountMoveLines()) {
                accountMoveLine.setJournal(journalCreated);
                LOGGER.debug("Creating a new child AccountMoveLine with information: {}", accountMoveLine);
                accountMoveLineService.create(accountMoveLine);
            }
        }
        return journalCreated;
    }

	@Transactional(readOnly = true, value = "dbinvoiceTransactionManager")
	@Override
	public Journal getById(Integer journalId) throws EntityNotFoundException {
        LOGGER.debug("Finding Journal by id: {}", journalId);
        Journal journal = this.wmGenericDao.findById(journalId);
        if (journal == null){
            LOGGER.debug("No Journal found with id: {}", journalId);
            throw new EntityNotFoundException(String.valueOf(journalId));
        }
        return journal;
    }

    @Transactional(readOnly = true, value = "dbinvoiceTransactionManager")
	@Override
	public Journal findById(Integer journalId) {
        LOGGER.debug("Finding Journal by id: {}", journalId);
        return this.wmGenericDao.findById(journalId);
    }


	@Transactional(rollbackFor = EntityNotFoundException.class, value = "dbinvoiceTransactionManager")
	@Override
	public Journal update(Journal journal) throws EntityNotFoundException {
        LOGGER.debug("Updating Journal with information: {}", journal);
        this.wmGenericDao.update(journal);

        Integer journalId = journal.getId();

        return this.wmGenericDao.findById(journalId);
    }

    @Transactional(value = "dbinvoiceTransactionManager")
	@Override
	public Journal delete(Integer journalId) throws EntityNotFoundException {
        LOGGER.debug("Deleting Journal with id: {}", journalId);
        Journal deleted = this.wmGenericDao.findById(journalId);
        if (deleted == null) {
            LOGGER.debug("No Journal found with id: {}", journalId);
            throw new EntityNotFoundException(String.valueOf(journalId));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

	@Transactional(readOnly = true, value = "dbinvoiceTransactionManager")
	@Override
	public Page<Journal> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all Journals");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "dbinvoiceTransactionManager")
    @Override
    public Page<Journal> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all Journals");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "dbinvoiceTransactionManager")
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service dbinvoice for table Journal to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

	@Transactional(readOnly = true, value = "dbinvoiceTransactionManager")
	@Override
	public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "dbinvoiceTransactionManager")
	@Override
    public Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable) {
        return this.wmGenericDao.getAggregatedValues(aggregationInfo, pageable);
    }

    @Transactional(readOnly = true, value = "dbinvoiceTransactionManager")
    @Override
    public Page<AccountMove> findAssociatedAccountMoves(Integer id, Pageable pageable) {
        LOGGER.debug("Fetching all associated accountMoves");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("journal.id = '" + id + "'");

        return accountMoveService.findAll(queryBuilder.toString(), pageable);
    }

    @Transactional(readOnly = true, value = "dbinvoiceTransactionManager")
    @Override
    public Page<AccountMoveLine> findAssociatedAccountMoveLines(Integer id, Pageable pageable) {
        LOGGER.debug("Fetching all associated accountMoveLines");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("journal.id = '" + id + "'");

        return accountMoveLineService.findAll(queryBuilder.toString(), pageable);
    }

    /**
	 * This setter method should only be used by unit tests
	 *
	 * @param service AccountMoveService instance
	 */
	protected void setAccountMoveService(AccountMoveService service) {
        this.accountMoveService = service;
    }

    /**
	 * This setter method should only be used by unit tests
	 *
	 * @param service AccountMoveLineService instance
	 */
	protected void setAccountMoveLineService(AccountMoveLineService service) {
        this.accountMoveLineService = service;
    }

}

