/*Generated by WaveMaker Studio*/
package com.faturacaomodelo.dbinvoice.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.faturacaomodelo.dbinvoice.Product;
import com.faturacaomodelo.dbinvoice.ProductType;

/**
 * Service object for domain model class {@link ProductType}.
 */
public interface ProductTypeService {

    /**
     * Creates a new ProductType. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on ProductType if any.
     *
     * @param productType Details of the ProductType to be created; value cannot be null.
     * @return The newly created ProductType.
     */
	ProductType create(ProductType productType);


	/**
	 * Returns ProductType by given id if exists.
	 *
	 * @param producttypeId The id of the ProductType to get; value cannot be null.
	 * @return ProductType associated with the given producttypeId.
     * @throws EntityNotFoundException If no ProductType is found.
	 */
	ProductType getById(Integer producttypeId) throws EntityNotFoundException;

    /**
	 * Find and return the ProductType by given id if exists, returns null otherwise.
	 *
	 * @param producttypeId The id of the ProductType to get; value cannot be null.
	 * @return ProductType associated with the given producttypeId.
	 */
	ProductType findById(Integer producttypeId);


	/**
	 * Updates the details of an existing ProductType. It replaces all fields of the existing ProductType with the given productType.
	 *
     * This method overrides the input field values using Server side or database managed properties defined on ProductType if any.
     *
	 * @param productType The details of the ProductType to be updated; value cannot be null.
	 * @return The updated ProductType.
	 * @throws EntityNotFoundException if no ProductType is found with given input.
	 */
	ProductType update(ProductType productType) throws EntityNotFoundException;

    /**
	 * Deletes an existing ProductType with the given id.
	 *
	 * @param producttypeId The id of the ProductType to be deleted; value cannot be null.
	 * @return The deleted ProductType.
	 * @throws EntityNotFoundException if no ProductType found with the given id.
	 */
	ProductType delete(Integer producttypeId) throws EntityNotFoundException;

	/**
	 * Find all ProductTypes matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
	 *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
	 *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching ProductTypes.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
	 */
    @Deprecated
	Page<ProductType> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
	 * Find all ProductTypes matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching ProductTypes.
     *
     * @see Pageable
     * @see Page
	 */
    Page<ProductType> findAll(String query, Pageable pageable);

    /**
	 * Exports all ProductTypes matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
	 */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

	/**
	 * Retrieve the count of the ProductTypes in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
	 * @return The count of the ProductType.
	 */
	long count(String query);

	/**
	 * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
	 * @return Paginated data with included fields.

     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
	Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);

    /*
     * Returns the associated products for given ProductType id.
     *
     * @param id value of id; value cannot be null
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of associated Product instances.
     *
     * @see Pageable
     * @see Page
     */
    Page<Product> findAssociatedProducts(Integer id, Pageable pageable);

}

