/*Generated by WaveMaker Studio*/
package com.faturacaomodelo.dbinvoice.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.faturacaomodelo.dbinvoice.Product;
import com.faturacaomodelo.dbinvoice.ProductCategory;

/**
 * Service object for domain model class {@link ProductCategory}.
 */
public interface ProductCategoryService {

    /**
     * Creates a new ProductCategory. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on ProductCategory if any.
     *
     * @param productCategory Details of the ProductCategory to be created; value cannot be null.
     * @return The newly created ProductCategory.
     */
	ProductCategory create(ProductCategory productCategory);


	/**
	 * Returns ProductCategory by given id if exists.
	 *
	 * @param productcategoryId The id of the ProductCategory to get; value cannot be null.
	 * @return ProductCategory associated with the given productcategoryId.
     * @throws EntityNotFoundException If no ProductCategory is found.
	 */
	ProductCategory getById(Integer productcategoryId) throws EntityNotFoundException;

    /**
	 * Find and return the ProductCategory by given id if exists, returns null otherwise.
	 *
	 * @param productcategoryId The id of the ProductCategory to get; value cannot be null.
	 * @return ProductCategory associated with the given productcategoryId.
	 */
	ProductCategory findById(Integer productcategoryId);


	/**
	 * Updates the details of an existing ProductCategory. It replaces all fields of the existing ProductCategory with the given productCategory.
	 *
     * This method overrides the input field values using Server side or database managed properties defined on ProductCategory if any.
     *
	 * @param productCategory The details of the ProductCategory to be updated; value cannot be null.
	 * @return The updated ProductCategory.
	 * @throws EntityNotFoundException if no ProductCategory is found with given input.
	 */
	ProductCategory update(ProductCategory productCategory) throws EntityNotFoundException;

    /**
	 * Deletes an existing ProductCategory with the given id.
	 *
	 * @param productcategoryId The id of the ProductCategory to be deleted; value cannot be null.
	 * @return The deleted ProductCategory.
	 * @throws EntityNotFoundException if no ProductCategory found with the given id.
	 */
	ProductCategory delete(Integer productcategoryId) throws EntityNotFoundException;

	/**
	 * Find all ProductCategories matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
	 *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
	 *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching ProductCategories.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
	 */
    @Deprecated
	Page<ProductCategory> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
	 * Find all ProductCategories matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching ProductCategories.
     *
     * @see Pageable
     * @see Page
	 */
    Page<ProductCategory> findAll(String query, Pageable pageable);

    /**
	 * Exports all ProductCategories matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
	 */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

	/**
	 * Retrieve the count of the ProductCategories in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
	 * @return The count of the ProductCategory.
	 */
	long count(String query);

	/**
	 * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
	 * @return Paginated data with included fields.

     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
	Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);

    /*
     * Returns the associated products for given ProductCategory id.
     *
     * @param id value of id; value cannot be null
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of associated Product instances.
     *
     * @see Pageable
     * @see Page
     */
    Page<Product> findAssociatedProducts(Integer id, Pageable pageable);

}

