/*Generated by WaveMaker Studio*/
package com.faturacaomodelo.dbinvoice.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.faturacaomodelo.dbinvoice.QuotationLine;

/**
 * Service object for domain model class {@link QuotationLine}.
 */
public interface QuotationLineService {

    /**
     * Creates a new QuotationLine. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on QuotationLine if any.
     *
     * @param quotationLine Details of the QuotationLine to be created; value cannot be null.
     * @return The newly created QuotationLine.
     */
	QuotationLine create(QuotationLine quotationLine);


	/**
	 * Returns QuotationLine by given id if exists.
	 *
	 * @param quotationlineId The id of the QuotationLine to get; value cannot be null.
	 * @return QuotationLine associated with the given quotationlineId.
     * @throws EntityNotFoundException If no QuotationLine is found.
	 */
	QuotationLine getById(Integer quotationlineId) throws EntityNotFoundException;

    /**
	 * Find and return the QuotationLine by given id if exists, returns null otherwise.
	 *
	 * @param quotationlineId The id of the QuotationLine to get; value cannot be null.
	 * @return QuotationLine associated with the given quotationlineId.
	 */
	QuotationLine findById(Integer quotationlineId);


	/**
	 * Updates the details of an existing QuotationLine. It replaces all fields of the existing QuotationLine with the given quotationLine.
	 *
     * This method overrides the input field values using Server side or database managed properties defined on QuotationLine if any.
     *
	 * @param quotationLine The details of the QuotationLine to be updated; value cannot be null.
	 * @return The updated QuotationLine.
	 * @throws EntityNotFoundException if no QuotationLine is found with given input.
	 */
	QuotationLine update(QuotationLine quotationLine) throws EntityNotFoundException;

    /**
	 * Deletes an existing QuotationLine with the given id.
	 *
	 * @param quotationlineId The id of the QuotationLine to be deleted; value cannot be null.
	 * @return The deleted QuotationLine.
	 * @throws EntityNotFoundException if no QuotationLine found with the given id.
	 */
	QuotationLine delete(Integer quotationlineId) throws EntityNotFoundException;

	/**
	 * Find all QuotationLines matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
	 *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
	 *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching QuotationLines.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
	 */
    @Deprecated
	Page<QuotationLine> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
	 * Find all QuotationLines matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching QuotationLines.
     *
     * @see Pageable
     * @see Page
	 */
    Page<QuotationLine> findAll(String query, Pageable pageable);

    /**
	 * Exports all QuotationLines matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
	 */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

	/**
	 * Retrieve the count of the QuotationLines in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
	 * @return The count of the QuotationLine.
	 */
	long count(String query);

	/**
	 * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
	 * @return Paginated data with included fields.

     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
	Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);


}

