/*Generated by WaveMaker Studio*/
package com.faturacaomodelo.dbinvoice.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.faturacaomodelo.dbinvoice.Settings;


/**
 * ServiceImpl object for domain model class Settings.
 *
 * @see Settings
 */
@Service("dbinvoice.SettingsService")
public class SettingsServiceImpl implements SettingsService {

    private static final Logger LOGGER = LoggerFactory.getLogger(SettingsServiceImpl.class);


    @Autowired
    @Qualifier("dbinvoice.SettingsDao")
    private WMGenericDao<Settings, Integer> wmGenericDao;

    public void setWMGenericDao(WMGenericDao<Settings, Integer> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "dbinvoiceTransactionManager")
    @Override
	public Settings create(Settings settings) {
        LOGGER.debug("Creating a new Settings with information: {}", settings);
        Settings settingsCreated = this.wmGenericDao.create(settings);
        return settingsCreated;
    }

	@Transactional(readOnly = true, value = "dbinvoiceTransactionManager")
	@Override
	public Settings getById(Integer settingsId) throws EntityNotFoundException {
        LOGGER.debug("Finding Settings by id: {}", settingsId);
        Settings settings = this.wmGenericDao.findById(settingsId);
        if (settings == null){
            LOGGER.debug("No Settings found with id: {}", settingsId);
            throw new EntityNotFoundException(String.valueOf(settingsId));
        }
        return settings;
    }

    @Transactional(readOnly = true, value = "dbinvoiceTransactionManager")
	@Override
	public Settings findById(Integer settingsId) {
        LOGGER.debug("Finding Settings by id: {}", settingsId);
        return this.wmGenericDao.findById(settingsId);
    }


	@Transactional(rollbackFor = EntityNotFoundException.class, value = "dbinvoiceTransactionManager")
	@Override
	public Settings update(Settings settings) throws EntityNotFoundException {
        LOGGER.debug("Updating Settings with information: {}", settings);
        this.wmGenericDao.update(settings);

        Integer settingsId = settings.getId();

        return this.wmGenericDao.findById(settingsId);
    }

    @Transactional(value = "dbinvoiceTransactionManager")
	@Override
	public Settings delete(Integer settingsId) throws EntityNotFoundException {
        LOGGER.debug("Deleting Settings with id: {}", settingsId);
        Settings deleted = this.wmGenericDao.findById(settingsId);
        if (deleted == null) {
            LOGGER.debug("No Settings found with id: {}", settingsId);
            throw new EntityNotFoundException(String.valueOf(settingsId));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

	@Transactional(readOnly = true, value = "dbinvoiceTransactionManager")
	@Override
	public Page<Settings> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all Settings");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "dbinvoiceTransactionManager")
    @Override
    public Page<Settings> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all Settings");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "dbinvoiceTransactionManager")
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service dbinvoice for table Settings to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

	@Transactional(readOnly = true, value = "dbinvoiceTransactionManager")
	@Override
	public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "dbinvoiceTransactionManager")
	@Override
    public Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable) {
        return this.wmGenericDao.getAggregatedValues(aggregationInfo, pageable);
    }



}

