/*Generated by WaveMaker Studio*/

package com.faturacaomodelo.db_a_account_id.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


public interface Db_a_account_idProcedureExecutorService {


}


