/*Generated by WaveMaker Studio*/

package com.faturacaomodelo.dbc4b_1.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Service;

import com.wavemaker.runtime.data.dao.query.WMQueryExecutor;

@Service
public class DbC4B_1QueryExecutorServiceImpl implements DbC4B_1QueryExecutorService {

    private static final Logger LOGGER = LoggerFactory.getLogger(DbC4B_1QueryExecutorServiceImpl.class);

    @Autowired
    @Qualifier("dbC4B_1WMQueryExecutor")
    private WMQueryExecutor queryExecutor;


}


