/*Generated by WaveMaker Studio*/

package com.faturacaomodelo.dbc4b_1.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


public interface DbC4B_1QueryExecutorService {


}


