/*Generated by WaveMaker Studio*/
package com.faturacaomodelo.dbc4b.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.faturacaomodelo.dbc4b.BusinessPaymentMethodsRel;

/**
 * Service object for domain model class {@link BusinessPaymentMethodsRel}.
 */
public interface BusinessPaymentMethodsRelService {

    /**
     * Creates a new BusinessPaymentMethodsRel. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on BusinessPaymentMethodsRel if any.
     *
     * @param businessPaymentMethodsRel Details of the BusinessPaymentMethodsRel to be created; value cannot be null.
     * @return The newly created BusinessPaymentMethodsRel.
     */
	BusinessPaymentMethodsRel create(BusinessPaymentMethodsRel businessPaymentMethodsRel);


	/**
	 * Returns BusinessPaymentMethodsRel by given id if exists.
	 *
	 * @param businesspaymentmethodsrelId The id of the BusinessPaymentMethodsRel to get; value cannot be null.
	 * @return BusinessPaymentMethodsRel associated with the given businesspaymentmethodsrelId.
     * @throws EntityNotFoundException If no BusinessPaymentMethodsRel is found.
	 */
	BusinessPaymentMethodsRel getById(Integer businesspaymentmethodsrelId) throws EntityNotFoundException;

    /**
	 * Find and return the BusinessPaymentMethodsRel by given id if exists, returns null otherwise.
	 *
	 * @param businesspaymentmethodsrelId The id of the BusinessPaymentMethodsRel to get; value cannot be null.
	 * @return BusinessPaymentMethodsRel associated with the given businesspaymentmethodsrelId.
	 */
	BusinessPaymentMethodsRel findById(Integer businesspaymentmethodsrelId);


	/**
	 * Updates the details of an existing BusinessPaymentMethodsRel. It replaces all fields of the existing BusinessPaymentMethodsRel with the given businessPaymentMethodsRel.
	 *
     * This method overrides the input field values using Server side or database managed properties defined on BusinessPaymentMethodsRel if any.
     *
	 * @param businessPaymentMethodsRel The details of the BusinessPaymentMethodsRel to be updated; value cannot be null.
	 * @return The updated BusinessPaymentMethodsRel.
	 * @throws EntityNotFoundException if no BusinessPaymentMethodsRel is found with given input.
	 */
	BusinessPaymentMethodsRel update(BusinessPaymentMethodsRel businessPaymentMethodsRel) throws EntityNotFoundException;

    /**
	 * Deletes an existing BusinessPaymentMethodsRel with the given id.
	 *
	 * @param businesspaymentmethodsrelId The id of the BusinessPaymentMethodsRel to be deleted; value cannot be null.
	 * @return The deleted BusinessPaymentMethodsRel.
	 * @throws EntityNotFoundException if no BusinessPaymentMethodsRel found with the given id.
	 */
	BusinessPaymentMethodsRel delete(Integer businesspaymentmethodsrelId) throws EntityNotFoundException;

	/**
	 * Find all BusinessPaymentMethodsRels matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
	 *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
	 *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching BusinessPaymentMethodsRels.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
	 */
    @Deprecated
	Page<BusinessPaymentMethodsRel> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
	 * Find all BusinessPaymentMethodsRels matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching BusinessPaymentMethodsRels.
     *
     * @see Pageable
     * @see Page
	 */
    Page<BusinessPaymentMethodsRel> findAll(String query, Pageable pageable);

    /**
	 * Exports all BusinessPaymentMethodsRels matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
	 */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

	/**
	 * Retrieve the count of the BusinessPaymentMethodsRels in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
	 * @return The count of the BusinessPaymentMethodsRel.
	 */
	long count(String query);

	/**
	 * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
	 * @return Paginated data with included fields.

     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
	Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);


}

