/*Generated by WaveMaker Studio*/
package com.faturacaomodelo.dbc4b.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.faturacaomodelo.dbc4b.DocumentMediaLibrary;

/**
 * Service object for domain model class {@link DocumentMediaLibrary}.
 */
public interface DocumentMediaLibraryService {

    /**
     * Creates a new DocumentMediaLibrary. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on DocumentMediaLibrary if any.
     *
     * @param documentMediaLibrary Details of the DocumentMediaLibrary to be created; value cannot be null.
     * @return The newly created DocumentMediaLibrary.
     */
	DocumentMediaLibrary create(DocumentMediaLibrary documentMediaLibrary);


	/**
	 * Returns DocumentMediaLibrary by given id if exists.
	 *
	 * @param documentmedialibraryId The id of the DocumentMediaLibrary to get; value cannot be null.
	 * @return DocumentMediaLibrary associated with the given documentmedialibraryId.
     * @throws EntityNotFoundException If no DocumentMediaLibrary is found.
	 */
	DocumentMediaLibrary getById(Integer documentmedialibraryId) throws EntityNotFoundException;

    /**
	 * Find and return the DocumentMediaLibrary by given id if exists, returns null otherwise.
	 *
	 * @param documentmedialibraryId The id of the DocumentMediaLibrary to get; value cannot be null.
	 * @return DocumentMediaLibrary associated with the given documentmedialibraryId.
	 */
	DocumentMediaLibrary findById(Integer documentmedialibraryId);


	/**
	 * Updates the details of an existing DocumentMediaLibrary. It replaces all fields of the existing DocumentMediaLibrary with the given documentMediaLibrary.
	 *
     * This method overrides the input field values using Server side or database managed properties defined on DocumentMediaLibrary if any.
     *
	 * @param documentMediaLibrary The details of the DocumentMediaLibrary to be updated; value cannot be null.
	 * @return The updated DocumentMediaLibrary.
	 * @throws EntityNotFoundException if no DocumentMediaLibrary is found with given input.
	 */
	DocumentMediaLibrary update(DocumentMediaLibrary documentMediaLibrary) throws EntityNotFoundException;

    /**
	 * Deletes an existing DocumentMediaLibrary with the given id.
	 *
	 * @param documentmedialibraryId The id of the DocumentMediaLibrary to be deleted; value cannot be null.
	 * @return The deleted DocumentMediaLibrary.
	 * @throws EntityNotFoundException if no DocumentMediaLibrary found with the given id.
	 */
	DocumentMediaLibrary delete(Integer documentmedialibraryId) throws EntityNotFoundException;

	/**
	 * Find all DocumentMediaLibraries matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
	 *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
	 *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching DocumentMediaLibraries.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
	 */
    @Deprecated
	Page<DocumentMediaLibrary> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
	 * Find all DocumentMediaLibraries matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching DocumentMediaLibraries.
     *
     * @see Pageable
     * @see Page
	 */
    Page<DocumentMediaLibrary> findAll(String query, Pageable pageable);

    /**
	 * Exports all DocumentMediaLibraries matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
	 */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

	/**
	 * Retrieve the count of the DocumentMediaLibraries in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
	 * @return The count of the DocumentMediaLibrary.
	 */
	long count(String query);

	/**
	 * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
	 * @return Paginated data with included fields.

     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
	Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);


}

