/*Generated by WaveMaker Studio*/
package com.faturacaomodelo.dbc4b.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.faturacaomodelo.dbc4b.InvoiceLine;
import com.faturacaomodelo.dbc4b.TaxInvoiceLineRel;

/**
 * Service object for domain model class {@link InvoiceLine}.
 */
public interface InvoiceLineService {

    /**
     * Creates a new InvoiceLine. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on InvoiceLine if any.
     *
     * @param invoiceLine Details of the InvoiceLine to be created; value cannot be null.
     * @return The newly created InvoiceLine.
     */
	InvoiceLine create(InvoiceLine invoiceLine);


	/**
	 * Returns InvoiceLine by given id if exists.
	 *
	 * @param invoicelineId The id of the InvoiceLine to get; value cannot be null.
	 * @return InvoiceLine associated with the given invoicelineId.
     * @throws EntityNotFoundException If no InvoiceLine is found.
	 */
	InvoiceLine getById(Integer invoicelineId) throws EntityNotFoundException;

    /**
	 * Find and return the InvoiceLine by given id if exists, returns null otherwise.
	 *
	 * @param invoicelineId The id of the InvoiceLine to get; value cannot be null.
	 * @return InvoiceLine associated with the given invoicelineId.
	 */
	InvoiceLine findById(Integer invoicelineId);


	/**
	 * Updates the details of an existing InvoiceLine. It replaces all fields of the existing InvoiceLine with the given invoiceLine.
	 *
     * This method overrides the input field values using Server side or database managed properties defined on InvoiceLine if any.
     *
	 * @param invoiceLine The details of the InvoiceLine to be updated; value cannot be null.
	 * @return The updated InvoiceLine.
	 * @throws EntityNotFoundException if no InvoiceLine is found with given input.
	 */
	InvoiceLine update(InvoiceLine invoiceLine) throws EntityNotFoundException;

    /**
	 * Deletes an existing InvoiceLine with the given id.
	 *
	 * @param invoicelineId The id of the InvoiceLine to be deleted; value cannot be null.
	 * @return The deleted InvoiceLine.
	 * @throws EntityNotFoundException if no InvoiceLine found with the given id.
	 */
	InvoiceLine delete(Integer invoicelineId) throws EntityNotFoundException;

	/**
	 * Find all InvoiceLines matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
	 *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
	 *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching InvoiceLines.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
	 */
    @Deprecated
	Page<InvoiceLine> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
	 * Find all InvoiceLines matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching InvoiceLines.
     *
     * @see Pageable
     * @see Page
	 */
    Page<InvoiceLine> findAll(String query, Pageable pageable);

    /**
	 * Exports all InvoiceLines matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
	 */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

	/**
	 * Retrieve the count of the InvoiceLines in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
	 * @return The count of the InvoiceLine.
	 */
	long count(String query);

	/**
	 * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
	 * @return Paginated data with included fields.

     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
	Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);

    /*
     * Returns the associated taxInvoiceLineRels for given InvoiceLine id.
     *
     * @param id value of id; value cannot be null
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of associated TaxInvoiceLineRel instances.
     *
     * @see Pageable
     * @see Page
     */
    Page<TaxInvoiceLineRel> findAssociatedTaxInvoiceLineRels(Integer id, Pageable pageable);

}

