/*Generated by WaveMaker Studio*/
package com.faturacaomodelo.dbc4b.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.faturacaomodelo.dbc4b.Table42;

/**
 * Service object for domain model class {@link Table42}.
 */
public interface Table42Service {

    /**
     * Creates a new Table42. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on Table42 if any.
     *
     * @param table42 Details of the Table42 to be created; value cannot be null.
     * @return The newly created Table42.
     */
	Table42 create(Table42 table42);


	/**
	 * Returns Table42 by given id if exists.
	 *
	 * @param table42Id The id of the Table42 to get; value cannot be null.
	 * @return Table42 associated with the given table42Id.
     * @throws EntityNotFoundException If no Table42 is found.
	 */
	Table42 getById(Integer table42Id) throws EntityNotFoundException;

    /**
	 * Find and return the Table42 by given id if exists, returns null otherwise.
	 *
	 * @param table42Id The id of the Table42 to get; value cannot be null.
	 * @return Table42 associated with the given table42Id.
	 */
	Table42 findById(Integer table42Id);


	/**
	 * Updates the details of an existing Table42. It replaces all fields of the existing Table42 with the given table42.
	 *
     * This method overrides the input field values using Server side or database managed properties defined on Table42 if any.
     *
	 * @param table42 The details of the Table42 to be updated; value cannot be null.
	 * @return The updated Table42.
	 * @throws EntityNotFoundException if no Table42 is found with given input.
	 */
	Table42 update(Table42 table42) throws EntityNotFoundException;

    /**
	 * Deletes an existing Table42 with the given id.
	 *
	 * @param table42Id The id of the Table42 to be deleted; value cannot be null.
	 * @return The deleted Table42.
	 * @throws EntityNotFoundException if no Table42 found with the given id.
	 */
	Table42 delete(Integer table42Id) throws EntityNotFoundException;

	/**
	 * Find all Table42s matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
	 *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
	 *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Table42s.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
	 */
    @Deprecated
	Page<Table42> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
	 * Find all Table42s matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Table42s.
     *
     * @see Pageable
     * @see Page
	 */
    Page<Table42> findAll(String query, Pageable pageable);

    /**
	 * Exports all Table42s matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
	 */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

	/**
	 * Retrieve the count of the Table42s in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
	 * @return The count of the Table42.
	 */
	long count(String query);

	/**
	 * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
	 * @return Paginated data with included fields.

     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
	Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);


}

