/*Generated by WaveMaker Studio*/
package com.faturacaomodelo.dbc4b.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.faturacaomodelo.dbc4b.Translation;


/**
 * ServiceImpl object for domain model class Translation.
 *
 * @see Translation
 */
@Service("dbC4B.TranslationService")
public class TranslationServiceImpl implements TranslationService {

    private static final Logger LOGGER = LoggerFactory.getLogger(TranslationServiceImpl.class);


    @Autowired
    @Qualifier("dbC4B.TranslationDao")
    private WMGenericDao<Translation, Integer> wmGenericDao;

    public void setWMGenericDao(WMGenericDao<Translation, Integer> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "dbC4BTransactionManager")
    @Override
	public Translation create(Translation translationInstance) {
        LOGGER.debug("Creating a new Translation with information: {}", translationInstance);
        Translation translationInstanceCreated = this.wmGenericDao.create(translationInstance);
        return translationInstanceCreated;
    }

	@Transactional(readOnly = true, value = "dbC4BTransactionManager")
	@Override
	public Translation getById(Integer translationId) throws EntityNotFoundException {
        LOGGER.debug("Finding Translation by id: {}", translationId);
        Translation translationInstance = this.wmGenericDao.findById(translationId);
        if (translationInstance == null){
            LOGGER.debug("No Translation found with id: {}", translationId);
            throw new EntityNotFoundException(String.valueOf(translationId));
        }
        return translationInstance;
    }

    @Transactional(readOnly = true, value = "dbC4BTransactionManager")
	@Override
	public Translation findById(Integer translationId) {
        LOGGER.debug("Finding Translation by id: {}", translationId);
        return this.wmGenericDao.findById(translationId);
    }


	@Transactional(rollbackFor = EntityNotFoundException.class, value = "dbC4BTransactionManager")
	@Override
	public Translation update(Translation translationInstance) throws EntityNotFoundException {
        LOGGER.debug("Updating Translation with information: {}", translationInstance);
        this.wmGenericDao.update(translationInstance);

        Integer translationId = translationInstance.getId();

        return this.wmGenericDao.findById(translationId);
    }

    @Transactional(value = "dbC4BTransactionManager")
	@Override
	public Translation delete(Integer translationId) throws EntityNotFoundException {
        LOGGER.debug("Deleting Translation with id: {}", translationId);
        Translation deleted = this.wmGenericDao.findById(translationId);
        if (deleted == null) {
            LOGGER.debug("No Translation found with id: {}", translationId);
            throw new EntityNotFoundException(String.valueOf(translationId));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

	@Transactional(readOnly = true, value = "dbC4BTransactionManager")
	@Override
	public Page<Translation> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all Translations");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "dbC4BTransactionManager")
    @Override
    public Page<Translation> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all Translations");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "dbC4BTransactionManager")
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service dbC4B for table Translation to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

	@Transactional(readOnly = true, value = "dbC4BTransactionManager")
	@Override
	public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "dbC4BTransactionManager")
	@Override
    public Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable) {
        return this.wmGenericDao.getAggregatedValues(aggregationInfo, pageable);
    }



}

