/*Generated by WaveMaker Studio*/
package com.faturacaomodelo.dbc4b;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

/**
 * Business generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`business`")
public class Business implements Serializable {

    private Integer id;
    private Integer partnerId;
    private String name;
    private String logo;
    private String categoryList;
    private String businessType;
    private String companyType;
    private Integer documentTemplateId;
    private DocumentTemplate documentTemplate;
    private Partner partner;
    private List<AccountMove> accountMoves;
    private List<AccountMoveLine> accountMoveLines;
    private List<BusinessPaymentMethodsRel> businessPaymentMethodsRels;
    private List<Currency> currencies;
    private List<Invoice> invoices;
    private List<Journal> journals;
    private List<PartnerBusinessRel> partnerBusinessRels;
    private List<PaymentTerm> paymentTerms;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`ID`", nullable = false, scale = 0, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "`partner_id`", nullable = true, scale = 0, precision = 10)
    public Integer getPartnerId() {
        return this.partnerId;
    }

    public void setPartnerId(Integer partnerId) {
        this.partnerId = partnerId;
    }

    @Column(name = "`name`", nullable = true, length = 255)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "`logo`", nullable = true, length = 255)
    public String getLogo() {
        return this.logo;
    }

    public void setLogo(String logo) {
        this.logo = logo;
    }

    @Column(name = "`categoryList`", nullable = true, length = 255)
    public String getCategoryList() {
        return this.categoryList;
    }

    public void setCategoryList(String categoryList) {
        this.categoryList = categoryList;
    }

    @Column(name = "`businessType`", nullable = true, length = 255)
    public String getBusinessType() {
        return this.businessType;
    }

    public void setBusinessType(String businessType) {
        this.businessType = businessType;
    }

    @Column(name = "`companyType`", nullable = true, length = 255)
    public String getCompanyType() {
        return this.companyType;
    }

    public void setCompanyType(String companyType) {
        this.companyType = companyType;
    }

    @Column(name = "`documentTemplate_id`", nullable = true, scale = 0, precision = 10)
    public Integer getDocumentTemplateId() {
        return this.documentTemplateId;
    }

    public void setDocumentTemplateId(Integer documentTemplateId) {
        this.documentTemplateId = documentTemplateId;
    }

    
    
    public DocumentTemplate getDocumentTemplate() {
        return this.documentTemplate;
    }

    public void setDocumentTemplate(DocumentTemplate documentTemplate) {
        if(documentTemplate != null) {
            this.documentTemplateId = documentTemplate.getId();
        }

        this.documentTemplate = documentTemplate;
    }

    
    
    public Partner getPartner() {
        return this.partner;
    }

    public void setPartner(Partner partner) {
        if(partner != null) {
            this.partnerId = partner.getId();
        }

        this.partner = partner;
    }

    @JsonInclude(Include.NON_EMPTY)
    
    public List<AccountMove> getAccountMoves() {
        return this.accountMoves;
    }

    public void setAccountMoves(List<AccountMove> accountMoves) {
        this.accountMoves = accountMoves;
    }

    @JsonInclude(Include.NON_EMPTY)
    
    public List<AccountMoveLine> getAccountMoveLines() {
        return this.accountMoveLines;
    }

    public void setAccountMoveLines(List<AccountMoveLine> accountMoveLines) {
        this.accountMoveLines = accountMoveLines;
    }

    @JsonInclude(Include.NON_EMPTY)
    
    public List<BusinessPaymentMethodsRel> getBusinessPaymentMethodsRels() {
        return this.businessPaymentMethodsRels;
    }

    public void setBusinessPaymentMethodsRels(List<BusinessPaymentMethodsRel> businessPaymentMethodsRels) {
        this.businessPaymentMethodsRels = businessPaymentMethodsRels;
    }

    @JsonInclude(Include.NON_EMPTY)
    
    public List<Currency> getCurrencies() {
        return this.currencies;
    }

    public void setCurrencies(List<Currency> currencies) {
        this.currencies = currencies;
    }

    @JsonInclude(Include.NON_EMPTY)
    
    public List<Invoice> getInvoices() {
        return this.invoices;
    }

    public void setInvoices(List<Invoice> invoices) {
        this.invoices = invoices;
    }

    @JsonInclude(Include.NON_EMPTY)
    
    public List<Journal> getJournals() {
        return this.journals;
    }

    public void setJournals(List<Journal> journals) {
        this.journals = journals;
    }

    @JsonInclude(Include.NON_EMPTY)
    
    public List<PartnerBusinessRel> getPartnerBusinessRels() {
        return this.partnerBusinessRels;
    }

    public void setPartnerBusinessRels(List<PartnerBusinessRel> partnerBusinessRels) {
        this.partnerBusinessRels = partnerBusinessRels;
    }

    @JsonInclude(Include.NON_EMPTY)
    
    public List<PaymentTerm> getPaymentTerms() {
        return this.paymentTerms;
    }

    public void setPaymentTerms(List<PaymentTerm> paymentTerms) {
        this.paymentTerms = paymentTerms;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Business)) return false;
        final Business business = (Business) o;
        return Objects.equals(getId(), business.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}

