/*Generated by WaveMaker Studio*/
package com.faturacaomodelo.dbc4b;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.sql.Date;
import java.util.List;
import java.util.Objects;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

/**
 * Country generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`country`")
public class Country implements Serializable {

    private Integer id;
    private Integer languageId;
    private Integer currencyId;
    private String currencyFormat;
    private Date dateFormat;
    private Integer timezoneId;
    private String name;
    private Timezone timezone;
    private Language language;
    private Currency currency;
    private List<FiscalPosition> fiscalPositions;
    private List<PaymentMethods> paymentMethodses;
    private List<Tax> taxes;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`ID`", nullable = false, scale = 0, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "`language_id`", nullable = true, scale = 0, precision = 10)
    public Integer getLanguageId() {
        return this.languageId;
    }

    public void setLanguageId(Integer languageId) {
        this.languageId = languageId;
    }

    @Column(name = "`currency_id`", nullable = true, scale = 0, precision = 10)
    public Integer getCurrencyId() {
        return this.currencyId;
    }

    public void setCurrencyId(Integer currencyId) {
        this.currencyId = currencyId;
    }

    @Column(name = "`currencyFormat`", nullable = true, length = 255)
    public String getCurrencyFormat() {
        return this.currencyFormat;
    }

    public void setCurrencyFormat(String currencyFormat) {
        this.currencyFormat = currencyFormat;
    }

    @Column(name = "`dateFormat`", nullable = true)
    public Date getDateFormat() {
        return this.dateFormat;
    }

    public void setDateFormat(Date dateFormat) {
        this.dateFormat = dateFormat;
    }

    @Column(name = "`timezone_id`", nullable = true, scale = 0, precision = 10)
    public Integer getTimezoneId() {
        return this.timezoneId;
    }

    public void setTimezoneId(Integer timezoneId) {
        this.timezoneId = timezoneId;
    }

    @Column(name = "`name`", nullable = true, length = 255)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    
    
    public Timezone getTimezone() {
        return this.timezone;
    }

    public void setTimezone(Timezone timezone) {
        if(timezone != null) {
            this.timezoneId = timezone.getId();
        }

        this.timezone = timezone;
    }

    
    
    public Language getLanguage() {
        return this.language;
    }

    public void setLanguage(Language language) {
        if(language != null) {
            this.languageId = language.getId();
        }

        this.language = language;
    }

    
    
    public Currency getCurrency() {
        return this.currency;
    }

    public void setCurrency(Currency currency) {
        if(currency != null) {
            this.currencyId = currency.getId();
        }

        this.currency = currency;
    }

    @JsonInclude(Include.NON_EMPTY)
    
    public List<FiscalPosition> getFiscalPositions() {
        return this.fiscalPositions;
    }

    public void setFiscalPositions(List<FiscalPosition> fiscalPositions) {
        this.fiscalPositions = fiscalPositions;
    }

    @JsonInclude(Include.NON_EMPTY)
    
    public List<PaymentMethods> getPaymentMethodses() {
        return this.paymentMethodses;
    }

    public void setPaymentMethodses(List<PaymentMethods> paymentMethodses) {
        this.paymentMethodses = paymentMethodses;
    }

    @JsonInclude(Include.NON_EMPTY)
    
    public List<Tax> getTaxes() {
        return this.taxes;
    }

    public void setTaxes(List<Tax> taxes) {
        this.taxes = taxes;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Country)) return false;
        final Country country = (Country) o;
        return Objects.equals(getId(), country.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}

