/*Generated by WaveMaker Studio*/
package com.faturacaomodelo.dbc4b;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Translation generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`translation`")
public class Translation implements Serializable {

    private Integer id;
    private String source;
    private String object;
    private String translation;
    private Integer languageId;
    private Language language;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`ID`", nullable = false, scale = 0, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "`source`", nullable = true, length = 255)
    public String getSource() {
        return this.source;
    }

    public void setSource(String source) {
        this.source = source;
    }

    @Column(name = "`object`", nullable = true, length = 255)
    public String getObject() {
        return this.object;
    }

    public void setObject(String object) {
        this.object = object;
    }

    @Column(name = "`translation`", nullable = true, length = 255)
    public String getTranslation() {
        return this.translation;
    }

    public void setTranslation(String translation) {
        this.translation = translation;
    }

    @Column(name = "`language_id`", nullable = true, scale = 0, precision = 10)
    public Integer getLanguageId() {
        return this.languageId;
    }

    public void setLanguageId(Integer languageId) {
        this.languageId = languageId;
    }

    
    
    public Language getLanguage() {
        return this.language;
    }

    public void setLanguage(Language language) {
        if(language != null) {
            this.languageId = language.getId();
        }

        this.language = language;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Translation)) return false;
        final Translation translationInstance = (Translation) o;
        return Objects.equals(getId(), translationInstance.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}

