/*Copyright (c) 2017-2018 multibase.pt All Rights Reserved.
 This software is the confidential and proprietary information of multibase.pt You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with multibase.pt*/
package com.faturacaomodelo.dbc4b_1;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.sql.Date;
import java.util.List;
import java.util.Objects;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

/**
 * AccountMove generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`accountMove`")
public class AccountMove implements Serializable {

    private Integer id;
    private String status;
    private Date date;
    private String movement;
    private Integer amount;
    private Integer paymentId;
    private Integer journalId;
    private Integer businessId;
    private Integer partnerId;
    private Journal journal;
    private Payment payment;
    private Business business;
    private Partner partner;
    private List<AccountMoveLine> accountMoveLines;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`ID`", nullable = false, scale = 0, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "`status`", nullable = true, length = 255)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Column(name = "`date`", nullable = true)
    public Date getDate() {
        return this.date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    @Column(name = "`movement`", nullable = true, length = 255)
    public String getMovement() {
        return this.movement;
    }

    public void setMovement(String movement) {
        this.movement = movement;
    }

    @Column(name = "`amount`", nullable = true, scale = 0, precision = 10)
    public Integer getAmount() {
        return this.amount;
    }

    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    @Column(name = "`payment_id`", nullable = true, scale = 0, precision = 10)
    public Integer getPaymentId() {
        return this.paymentId;
    }

    public void setPaymentId(Integer paymentId) {
        this.paymentId = paymentId;
    }

    @Column(name = "`journal_id`", nullable = true, scale = 0, precision = 10)
    public Integer getJournalId() {
        return this.journalId;
    }

    public void setJournalId(Integer journalId) {
        this.journalId = journalId;
    }

    @Column(name = "`business_id`", nullable = true, scale = 0, precision = 10)
    public Integer getBusinessId() {
        return this.businessId;
    }

    public void setBusinessId(Integer businessId) {
        this.businessId = businessId;
    }

    @Column(name = "`partner_id`", nullable = true, scale = 0, precision = 10)
    public Integer getPartnerId() {
        return this.partnerId;
    }

    public void setPartnerId(Integer partnerId) {
        this.partnerId = partnerId;
    }

    
    
    public Journal getJournal() {
        return this.journal;
    }

    public void setJournal(Journal journal) {
        if(journal != null) {
            this.journalId = journal.getId();
        }

        this.journal = journal;
    }

    
    
    public Payment getPayment() {
        return this.payment;
    }

    public void setPayment(Payment payment) {
        if(payment != null) {
            this.paymentId = payment.getId();
        }

        this.payment = payment;
    }

    
    
    public Business getBusiness() {
        return this.business;
    }

    public void setBusiness(Business business) {
        if(business != null) {
            this.businessId = business.getId();
        }

        this.business = business;
    }

    
    
    public Partner getPartner() {
        return this.partner;
    }

    public void setPartner(Partner partner) {
        if(partner != null) {
            this.partnerId = partner.getId();
        }

        this.partner = partner;
    }

    @JsonInclude(Include.NON_EMPTY)
    
    public List<AccountMoveLine> getAccountMoveLines() {
        return this.accountMoveLines;
    }

    public void setAccountMoveLines(List<AccountMoveLine> accountMoveLines) {
        this.accountMoveLines = accountMoveLines;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof AccountMove)) return false;
        final AccountMove accountMove = (AccountMove) o;
        return Objects.equals(getId(), accountMove.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}

