/*Copyright (c) 2017-2018 multibase.pt All Rights Reserved.
 This software is the confidential and proprietary information of multibase.pt You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with multibase.pt*/

package com.faturacaomodelo.db_systemcontrol.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Service;

import com.wavemaker.runtime.data.dao.procedure.WMProcedureExecutor;

@Service
public class DB_SystemControlProcedureExecutorServiceImpl implements DB_SystemControlProcedureExecutorService {

    private static final Logger LOGGER = LoggerFactory.getLogger(DB_SystemControlProcedureExecutorServiceImpl.class);

    @Autowired
    @Qualifier("DB_SystemControlWMProcedureExecutor")
    private WMProcedureExecutor procedureExecutor;


}


