/*Generated by WaveMaker Studio*/

package com.faturacaomodelo.db_systemcontrol.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.HashMap;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.wavemaker.runtime.data.dao.query.WMQueryExecutor;

import com.faturacaomodelo.db_systemcontrol.models.query.UpdatepasswordRequest;

@Service
public class DB_SystemControlQueryExecutorServiceImpl implements DB_SystemControlQueryExecutorService {

    private static final Logger LOGGER = LoggerFactory.getLogger(DB_SystemControlQueryExecutorServiceImpl.class);

    @Autowired
    @Qualifier("DB_SystemControlWMQueryExecutor")
    private WMQueryExecutor queryExecutor;

    @Transactional(value = "DB_SystemControlTransactionManager")
    @Override
    public Integer executeUpdatepassword(UpdatepasswordRequest updatepasswordRequest) {
        Map params = new HashMap(2);

        params.put("pwd", updatepasswordRequest.getPwd());
        params.put("email", updatepasswordRequest.getEmail());

        return queryExecutor.executeNamedQueryForUpdate("updatepassword", params);
    }

}


